version: '2'
services:
  frontend:
    build:
      context: ../parelpracht-client
      dockerfile: Dockerfile
    image: yoronex/parelpracht-client:latest
    ports:
      - '9639:80'
    networks:
      - parelpracht
    volumes:
      - logos:/usr/src/app/data/logos
      - backgrounds:/usr/src/app/data/backgrounds
  backend:
    build: ../parelpracht-server
    image: yoronex/parelpracht-server:latest
    networks:
      - parelpracht
    volumes:
      - backend-files:/usr/src/app/data
      - logos:/usr/src/app/data/logos
      - backgrounds:/usr/src/app/data/backgrounds
    environment:
      - PORT=3001
      - USE_HTTPS=false
      - SERVER_HOST=localhost:39390
      - TYPEORM_CONNECTION=postgres
      - TYPEORM_HOST=database
      - TYPEORM_PORT=5432
      - TYPEORM_DATABASE=parelpracht
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=ParelPassword3939
      - TYPEORM_SYNCHRONIZE=true
      - TYPEORM_LOGGING=false
      - TYPEORM_ENTITIES=dist/entity/**/*.js
      - TYPEORM_MIGRATIONS=dist/migration/**/*.js
      - TYPEORM_SUBSCRIBERS=dist/subscriber/**/*.js
      - SESSION_SECRET=SecretKeyForParelPracht3939VoVo39VoPeaches
      - MAIL_HOST=mail.example.com
      - MAIL_PORT=465
      - MAIL_USER=parelpracht@example.com
      - MAIL_PASSWORD=password
      - MAIL_FROM=ParelPracht <parelpracht@example.com>
      # The following environment variables are used by the DirectMail plugin
      # This is optional and thus these variables can be removed (if not used)
      - DIRECTMAIL_URL=
      - DIRECTMAIL_USERNAME=
      - DIRECTMAIL_PASSWORD=
      - DIRECTMAIL_PRODUCT_ID=
    depends_on:
      - database
# If you do not have a database available somewhere on the server, you can use this one. Do
# not forget to enable the database-data volume to make sure the database remains persistent.
#  database:
#    image: postgres
#    volumes:
#      - database-data:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=ParelPassword3939
#      - POSTGRES_DB=parelpracht
#    networks:
#      - parelpracht
volumes:
#  database-data:
#    driver: local
  backend-files:
    driver: local
  logos:
    driver: local
  backgrounds:
    driver: local
networks:
  parelpracht:
    driver: bridge

